### ISSUE TITLE
Crash on initial setup - java sample

### ISSUE THREAD

**Issue by melikabarzegaran** [shadowalker77/VersionControl#2]
```
2018-07-17 09:44:08.188 10598-10598/ir.ayantech.versioncontroljavasample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ir.ayantech.versioncontroljavasample, PID: 10598
    java.lang.RuntimeException: Unable to get provider ir.ayantech.versioncontrol.MyFileProvider: java.lang.ClassNotFoundException: Didn't find class "ir.ayantech.versioncontrol.MyFileProvider" on path: DexPathList[[zip file "/data/app/ir.ayantech.versioncontroljavasample-1/base.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_dependencies_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_0_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_1_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_2_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_3_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_4_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_5_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_6_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_7_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_8_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/ir.ayantech.versioncontroljavasample-1/lib/arm, /system/lib, /vendor/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6423)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6012)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5951)
        at android.app.ActivityThread.-wrap3(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "ir.ayantech.versioncontrol.MyFileProvider" on path: DexPathList[[zip file "/data/app/ir.ayantech.versioncontroljavasample-1/base.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_dependencies_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_0_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_1_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_2_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_3_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_4_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_5_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_6_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_7_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_8_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/ir.ayantech.versioncontroljavasample-1/lib/arm, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6408)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6012) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5951) 
        at android.app.ActivityThread.-wrap3(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6776) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/FileProvider;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
2018-07-17 09:44:08.188 10598-10598/ir.ayantech.versioncontroljavasample E/AndroidRuntime: 		... 12 more
    	Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/ir.ayantech.versioncontroljavasample-1/base.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_dependencies_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_0_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_1_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_2_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_3_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_4_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_5_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_6_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_7_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_8_apk.apk", zip file "/data/app/ir.ayantech.versioncontroljavasample-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/ir.ayantech.versioncontroljavasample-1/lib/arm, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 15 more
```

**Comment by melikabarzegaran** [comment]
kotlin sample also has the same problem.

```
2018-07-17 10:31:34.520 16050-16050/ir.ayantech.versioncontrolkotlinsample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ir.ayantech.versioncontrolkotlinsample, PID: 16050
    java.lang.RuntimeException: Unable to get provider ir.ayantech.versioncontrol.MyFileProvider: java.lang.ClassNotFoundException: Didn't find class "ir.ayantech.versioncontrol.MyFileProvider" on path: DexPathList[[zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/base.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_dependencies_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_0_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_1_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_2_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_3_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_4_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_5_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_6_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_7_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_8_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/ir.ayantech.versioncontrolkotlinsample-1/lib/arm, /system/lib, /vendor/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6423)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6012)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5951)
        at android.app.ActivityThread.-wrap3(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "ir.ayantech.versioncontrol.MyFileProvider" on path: DexPathList[[zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/base.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_dependencies_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_0_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_1_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_2_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_3_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_4_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_5_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_6_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_7_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_8_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/ir.ayantech.versioncontrolkotlinsample-1/lib/arm, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6408)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6012) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5951) 
        at android.app.ActivityThread.-wrap3(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6776) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/FileProvider;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
2018-07-17 10:31:34.524 16050-16050/ir.ayantech.versioncontrolkotlinsample E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
        		... 12 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/base.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_dependencies_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_0_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_1_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_2_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_3_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_4_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_5_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_6_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_7_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_8_apk.apk", zip file "/data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/ir.ayantech.versioncontrolkotlinsample-1/lib/arm, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 15 more
    		Suppressed: java.io.IOException: No original dex files found for dex location (arm) /data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_8_apk.apk ()
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:373)
        at dalvik.system.DexFile.<init>(DexFile.java:113)
        at dalvik.system.DexFile.<init>(DexFile.java:78)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:359)
        at dalvik.system.DexPathList.makeElements(DexPathList.java:323)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:263)
        at dalvik.system.DexPathList.<init>(DexPathList.java:126)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:48)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:58)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:535)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:568)
        at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:2053)
        at android.app.LoadedApk.getResources(LoadedApk.java:787)
        at android.app.ContextImpl.<init>(ContextImpl.java:2266)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2210)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2196)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5861)
        			... 8 more
    	[CIRCULAR REFERENCE:java.io.IOException: No original dex files found for dex location (arm) /data/app/ir.ayantech.versioncontrolkotlinsample-1/split_lib_slice_8_apk.apk ()]
```

**Comment by melikabarzegaran** [comment]
yeah, that was the problem. downgrading to the dependency below solved the problem.
```
implementation 'com.android.support:appcompat-v7:27.1.1'
```
